events {}

http {
    upstream backend {
        server apple-service:3006;
        server orange-service:3002;
        server grape-service:3003;
        server mango-service:3004;
        server pineapple-service:3005;
    }

    server {
        listen 443 ssl;

        location / {
            proxy_pass https://backend;
        }
    }
}