events {}

stream {

    upstream backend {
        server localhost:3005;
        server localhost:3004;
        server localhost:3003;
        server localhost:3002;
        # server 13.215.250.239;
    }
    
    server {
        listen 443;    

        proxy_pass backend;   
        proxy_next_upstream on;
    }
}