events {}

http {

    upstream backend {
        server 13.215.250.239;
        server localhost:3005;
        server localhost:3004;
        server localhost:3003;
        server localhost:3002;
    }
    
    server {
       listen 80 default_server;
       server_name localhost;
       
       return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name localhost;
        
        ssl_certificate      certificate.crt;
        ssl_certificate_key  private.key;
        real_ip_header   X-Real-IP;

        location / {
            proxy_pass https://backend;
        }
    }
}